language: node_js
node_js:
- 6.10.3
branches: 
only:
- master
- dev
deploy:
- provider: gae
  keyfile: "PPA2-app-2abc80ee29ef.json"
  project: "ppa2-app"
  no_promote: true
  version: "production"
  skip_cleanup: true
  on:
   branch: master
- provider: gae
  keyfile: "PPA2-app-2abc80ee29ef.json"
  project: "ppa2-app"
  no_promote: true
  version: "development"
  skip_cleanup: true
  on:
   branch: dev
  
before_install:
- openssl aes-256-cbc -K $encrypted_191cc3c8a684_key -iv $encrypted_191cc3c8a684_iv
  -in PPA2-app-2abc80ee29ef.json.enc -out PPA2-app-2abc80ee29ef.json -d
before_script:
  - if [ "$TRAVIS_BRANCH" = "dev" ]; then browserify imports.js --standalone bundle -o bundle.js
  - if [ "$TRAVIS_BRANCH" = "master" ]; then NODE_ENV=production browserify -g envify imports.js --standalone bundle -o bundle.js