language: node_js
node_js:
- 6.10.3
branches: 
only:
- master
- dev
deploy:
  skip_cleanup: true
  provider: gae
  keyfile: "PPA2-app-2abc80ee29ef.json"
  project: "ppa2-app"
  version: "production"
  on:
   branch: master
  provider: gae
  keyfile: "PPA2-app-2abc80ee29ef.json"
  project: "ppa2-app"
  version: "development"
  on:
   branch: dev
  
before_install:
- openssl aes-256-cbc -K $encrypted_191cc3c8a684_key -iv $encrypted_191cc3c8a684_iv
  -in PPA2-app-2abc80ee29ef.json.enc -out PPA2-app-2abc80ee29ef.json -d
