language: node_js
node_js:
- 6.10.3
branches:
  only:
  - master
  - dev
  - tmp_branch
before_install:
- openssl aes-256-cbc -K $encrypted_d83b0492b132_key -iv $encrypted_d83b0492b132_iv
  -in PPA2-dev-cecc60948cbc.json.enc -out PPA2-dev-cecc60948cbc.json -d
deploy:
  provider: gae
  keyfile: PPA2-dev-cecc60948cbc.json
  project: ppa2-dev
  no_promote: true
  skip_cleanup: true
